# -*- coding: utf-8 -*-
"""
***************************************************************************
WebMapExporter - A QGIS plugin
Export data (in cloud-native formats) and QGIS styling to build a standalone web map
Generated by Plugin Builder: http://jonah-sullivan.github.io/Qgis-Plugin-Builder/

    copyright            : (C) 2026 by Richard Thomas
    git sha              : $Format:%H$

 ***************************************************************************
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 ***************************************************************************
This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):
    """Load WebMapExporter class from file web_map_exporter.py.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .web_map_exporter import WebMapExporter
    return WebMapExporter(iface)
