# -*- coding: utf-8 -*-
"""
***************************************************************************
WebMapExporter - A QGIS plugin
Export data (in cloud-native formats) and QGIS styling to build a standalone web map
Generated by Plugin Builder: http://jonah-sullivan.github.io/Qgis-Plugin-Builder/

    Copyright            : (C) 2026 Richard Thomas
    Email                : mrcobristol-qgis@yahoo.com
    git sha              : $Format:%H$

 ***************************************************************************
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.*
 ***************************************************************************
This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):
    """Load WebMapExporter class from file web_map_exporter.py.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .web_map_exporter import WebMapExporter
    return WebMapExporter(iface)
