# -*- coding: utf-8 -*-
"""
***************************************************************************
WebMapExporter - A QGIS plugin
Export data (in cloud-native formats) and QGIS styling to build a standalone web map
Template generated by Plugin Builder: http://jonah-sullivan.github.io/Qgis-Plugin-Builder/

    copyright            : (C) 2026 by Richard Thomas
    git sha              : $Format:%H$

 ***************************************************************************
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 ***************************************************************************
Qt UI initialisation for plugin.
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import QUrl
from qgis.PyQt.QtGui import QDesktopServices

# Load .ui file so PyQt can populate plugin with elements from QtCreator
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'web_map_exporter_dialog_base.ui'))


class WebMapExporterDialog(QtWidgets.QDialog, FORM_CLASS):
    """Qt UI initialisation for 'Web Map Exporter' plugin.

    :param QtWidgets.QDialog: Qt6 UI dialog.
    :param FORM_CLASS: Loader for Qt6 UI elements from QtCreator .ui file.
    """

    def __init__(self, parent=None):
        """Initialize UI dialog and connect buttons to their handlers."""
        super(WebMapExporterDialog, self).__init__(parent)

        # Set up user interface designed in QtCreator through FORM_CLASS
        self.setupUi(self)

        # Connect main dialog "Help" button
        self.button_box_main_qt.helpRequested.connect(self.open_help_page)
        self.button_export_qt.clicked.connect(self._handle_export_click)

        self._export_handler = None

    def open_help_page(self):
        """Open documentation page in the system's default browser"""
        help_webpage_url = 'https://github.com/richard-thomas/qgis-web-map-exporter/blob/main/README.md'
        QDesktopServices.openUrl(QUrl(help_webpage_url))

    def set_export_handler(self, handler):
        """Register a callback to run when the export button is clicked."""
        self._export_handler = handler

    def _handle_export_click(self):
        """Run the registered export handler if one was provided."""
        if self._export_handler is not None:
            self._export_handler()
