# -*- coding: utf-8 -*-
"""
***************************************************************************
WebMapExporter - A QGIS plugin
Export data (in cloud-native formats) and QGIS styling to build a standalone web map
Template generated by Plugin Builder: http://jonah-sullivan.github.io/Qgis-Plugin-Builder/

    copyright            : (C) 2026 by Richard Thomas
    git sha              : $Format:%H$

 ***************************************************************************
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 ***************************************************************************
Initialisation and all handling of Qt UI for plugin.
"""

import os

from qgis.PyQt import uic
from qgis.PyQt.QtWidgets import QDialog, QTreeWidgetItem, QCheckBox, QLabel, QComboBox, QWidget, QHBoxLayout
from qgis.PyQt.QtCore import QUrl, Qt
from qgis.PyQt.QtGui import QDesktopServices
from qgis.core import QgsProject, QgsLayerTreeGroup, QgsMapLayer

from .file_export import FileExport

HELP_WEBPAGE_URL = 'https://github.com/richard-thomas/qgis-web-map-exporter/blob/main/README.md'

# Load .ui file so PyQt can populate plugin with elements from QtCreator
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'web_map_exporter_dialog_base.ui'))


class WebMapExporterDialog(QDialog, FORM_CLASS):
    """Initialisation and all handling of Qt UI for 'Web Map Exporter' plugin.

    :param QtWidgets.QDialog: Qt6 UI dialog.
    :param FORM_CLASS: Loader for Qt6 UI elements from QtCreator .ui file.
    """

    def __init__(self, plugin):
        """Initialize UI dialog and connect buttons to their handlers.

        :param plugin: QGIS plugin instance
        """
        super(WebMapExporterDialog, self).__init__(None)

        # Set up user interface designed in QtCreator through FORM_CLASS
        self.setupUi(self)


        # Connect main dialog "Help" and "Export" buttons
        self.file_export = FileExport(self, plugin)
        self.button_reload_qt.clicked.connect(self.load_project_layers)
        self.button_export_qt.clicked.connect(self._do_export)
        self.button_box_main_qt.helpRequested.connect(self._open_help_page)

    def log_message(self, message):
        """Write message to 'Output Log' tab in dialog window."""
        self.log_text_browser_qt.append(message)
        # TBD (optionally) write to folder on export

    def load_project_layers(self):
        """Fetch current project layers and populate the UI tree with layers only."""
        self.layers_tree_qt.clear()
        layer_nodes = QgsProject.instance().layerTreeRoot().children()
        self._populate_layer_tree(None, layer_nodes)
        self.layers_tree_qt.expandAll()

        # Switch tab to Layers tab so user can see new layer tree
        self.tab_widget_qt.setCurrentWidget(self.tab_layers_qt)

        # Set "Web Map Title" field from QGIS project title
        project_title = QgsProject.instance().title()
        self.options_title_qt.setText(project_title)

    def _do_export(self):
        """Export the layers selected in the dialog."""
        self.log_message("\nStarting Web Map Export...")

        # Get selected layers and their requested export formats from UI
        root = self.layers_tree_qt.invisibleRootItem()
        selected_layers = []
        for index in range(root.childCount()):
            item = root.child(index)
            self._collect_selected_layers(item, selected_layers)

        # Get list of layers in order of rendering (bottom layer first)
        # Define z_index (which gets passed on to web map config) such
        # that by default rendering order is reversed, but user can
        # tweak this manually in map config JSON if desired.
        layers_in_order = QgsProject.instance().layerTreeRoot().layerOrder()
        for layer_info in selected_layers:
            layer = layer_info["item"]
            if layer in layers_in_order:
                layer_info["z_index"] = -layers_in_order.index(layer) - 1
            else:
                layer_info["z_index"] = 0  # Layer not found in rendering order!

        # If no 'Output Display Projection' is entered, default to Web Mercator
        target_epsg = self.options_target_crs_qt.text()
        if target_epsg == "":
            target_epsg = "3857"
        # TBD: Do EPSG validation within Qt update handlers, so user gets
        # immediate feedback if they enter a non-numeric EPSG code.
        if not target_epsg.isdigit():
            self.log_message("ERROR: Invalid Output Display Projection EPSG code. Please enter a valid numeric EPSG code.")
            return
        ui_options = {
            "export_src_data": self.options_checkbox_src_data_qt.isChecked(),
            "pmtiles_max_zoom": self.options_pmtiles_max_zoom_qt.value(),
            "merge_pmtiles": self.options_checkbox_merge_pmtiles_qt.isChecked(),
            "compliant_geojson": self.options_checkbox_compliant_geojson_qt.isChecked(),
            "force_geoparquet_io": self.options_checkbox_gpq_io_qt.isChecked(),
            "export_slds": self.options_checkbox_slds_qt.isChecked(),
            "merge_slds": self.options_merge_slds_qt.isChecked(),
            "export_map_config": self.options_checkbox_map_qt.isChecked(),
            "web_map_title": self.options_title_qt.text(),
            "target_crs": "EPSG:" + target_epsg,
        }
        #self.log_message(str(ui_options))
        self.file_export.export_selected_layers(ui_options, selected_layers)

    def _open_help_page(self):
        """Open documentation page in the system's default browser"""
        QDesktopServices.openUrl(QUrl(HELP_WEBPAGE_URL))

    def _collect_selected_layers(self, item, selected_layers):
        """Get information from selected layers (only) of UI dialog."""
        if item.childCount() == 0:
            widget = self.layers_tree_qt.itemWidget(item, 0)
            if widget is None:
                return

            checkbox = widget.findChild(QCheckBox)
            if checkbox is None or not checkbox.isChecked():
                return

            label_widget = widget.findChild(QLabel)
            layer_name = label_widget.text()
            format_combobox = widget.findChild(QComboBox)
            layer_format = format_combobox.currentText()

            layer_item = self._find_layer_by_name(layer_name)
            if layer_item is None:
                self.log_message(f"WARNING: Skipping layer '{layer_name}' as not found in project")
                return
            if not layer_item.crs().isValid():
                self.log_message(
                    f"WARNING: Skipping layer '{layer_name}' as it has no valid CRS - set one in QGIS "
                    f"(Layer Properties ▸ Source) and re-export."
                )
                return
            selected_layers.append({
                "name": layer_name,
                "item": layer_item,
                "out_format": layer_format
            })
            return

        for child_index in range(item.childCount()):
            child_item = item.child(child_index)
            self._collect_selected_layers(child_item, selected_layers)

    def _find_layer_by_name(self, layer_name):
        """Find a layer in the current project by its tree name."""
        for layer in QgsProject.instance().mapLayers().values():
            if layer.name() == layer_name:
                return layer
        return None

    def _populate_layer_tree(self, parent_item, nodes):
        """Recursively add layer and group nodes to the UI tree."""
        for node in nodes:
            if isinstance(node, QgsLayerTreeGroup):
                # Add layer group to tree and recursively add its children
                #self.log_message(f'Traversing Group: {node.name()}')
                group_item = QTreeWidgetItem()
                group_item.setText(0, node.name())
                if parent_item is None:
                    self.layers_tree_qt.addTopLevelItem(group_item)
                else:
                    parent_item.addChild(group_item)
                self._populate_layer_tree(group_item, node.children())
            else:
                # Add layer to tree
                layer_item = QTreeWidgetItem()
                row_widget = QWidget()
                row_layout = QHBoxLayout(row_widget)
                row_layout.setContentsMargins(0, 0, 5, 0)
                row_layout.setSpacing(4)
                lyr_check_box = QCheckBox()
                lyr_label = QLabel(node.name())
                lyr_label.setAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
                lyr_combo_box = QComboBox()
                row_layout.addWidget(lyr_check_box, alignment=Qt.AlignmentFlag.AlignLeft)
                row_layout.addWidget(lyr_label, alignment=Qt.AlignmentFlag.AlignLeft)
                row_layout.addStretch(1)
                row_layout.addWidget(lyr_combo_box, alignment=Qt.AlignmentFlag.AlignRight)

                if node.layer().type() == QgsMapLayer.LayerType.Vector:
                    #self.log_message(f'Adding Vector Layer: {node.name()}')
                    lyr_combo_box.addItems(['FlatGeoBuf', 'PMTiles', 'GeoJSON', 'GeoParquet', '(Placeholder)'])
                else:
                    #self.log_message(
                    #    f'Adding Non-Vector Layer (Placeholder only): {node.name()}')
                    lyr_combo_box.addItems(['(Placeholder)'])
                    lyr_label.setStyleSheet('color: gray; font-style: italic;')

                if parent_item is None:
                    self.layers_tree_qt.addTopLevelItem(layer_item)
                else:
                    parent_item.addChild(layer_item)

                self.layers_tree_qt.setItemWidget(layer_item, 0, row_widget)
