# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WebMapExporter
                                 A QGIS plugin
 Export data (in cloud-native formats) and QGIS styling to build a standalone web map
 Generated by Plugin Builder: http://jonah-sullivan.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-23
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Richard Thomas
        email                : mrcobristol-qgis@yahoo.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QLocale, QTranslator, QCoreApplication, Qt
from qgis.core import QgsProject, QgsSettings, QgsLayerTreeGroup, QgsMapLayer, QgsSldExportContext, QgsVectorFileWriter, QgsCoordinateTransformContext
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QTreeWidgetItem, QCheckBox, QLabel, QComboBox, QWidget, QHBoxLayout, QFileDialog

# Import the code for the dialog
from .web_map_exporter_dialog import WebMapExporterDialog
import os.path

class WebMapExporter:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QgsSettings().value('locale/userLocale', QLocale().name())[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            '{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Web Map Exporter')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str

        :returns: Translated version of message.
        :rtype: str
        """
        return QCoreApplication.translate('WebMapExporter', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToWebMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(os.path.dirname(__file__), 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'Export data and styling'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginWebMenu(
                self.tr(u'&Web Map Exporter'),
                action)
            self.iface.removeToolBarIcon(action)

    def _populate_layer_tree(self, parent_item, nodes):
        """Recursively add layer and group nodes to the UI tree"""
        for node in nodes:
            if isinstance(node, QgsLayerTreeGroup):
                # Add layer group to tree and recursively add its children
                self.dlg.log_text_browser_qt.append(f"Traversing Group: {node.name()}")
                group_item = QTreeWidgetItem()
                group_item.setText(0, node.name())
                if parent_item is None:
                    self.dlg.layers_tree_qt.addTopLevelItem(group_item)
                else:
                    parent_item.addChild(group_item)
                self._populate_layer_tree(group_item, node.children())
            else:
                # Add layer to tree
                layer_item = QTreeWidgetItem()
                row_widget = QWidget()
                row_layout = QHBoxLayout(row_widget)
                row_layout.setContentsMargins(0, 0, 5, 0)
                row_layout.setSpacing(4)
                lyr_check_box = QCheckBox()
                lyr_label = QLabel(node.name())
                lyr_label.setAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
                lyr_combo_box = QComboBox()
                row_layout.addWidget(lyr_check_box, alignment=Qt.AlignmentFlag.AlignLeft)
                row_layout.addWidget(lyr_label, alignment=Qt.AlignmentFlag.AlignLeft)
                row_layout.addStretch(1)
                row_layout.addWidget(lyr_combo_box, alignment=Qt.AlignmentFlag.AlignRight)

                if node.layer().type() == QgsMapLayer.LayerType.Vector:
                    self.dlg.log_text_browser_qt.append(f"Adding Vector Layer: {node.name()}")
                    lyr_combo_box.addItems(["FlatGeoBuf", "PMTile", "GeoJSON", "GeoParquet", "(Placeholder)"])
                else:
                    self.dlg.log_text_browser_qt.append(
                        f"Adding Non-Vector Layer (Placeholder only): {node.name()}")
                    lyr_combo_box.addItems(["(Placeholder)"])
                    lyr_label.setStyleSheet("color: gray; font-style: italic;")

                if parent_item is None:
                    self.dlg.layers_tree_qt.addTopLevelItem(layer_item)
                else:
                    parent_item.addChild(layer_item)

                self.dlg.layers_tree_qt.setItemWidget(layer_item, 0, row_widget)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = WebMapExporterDialog()
            self.dlg.set_export_handler(self.export_layers)

        # Fetch current project layers and populate the UI tree with layers only
        self.dlg.layers_tree_qt.clear()
        layer_nodes = QgsProject.instance().layerTreeRoot().children()
        self._populate_layer_tree(None, layer_nodes)
        self.dlg.layers_tree_qt.expandAll()

        # Display the dialog
        self.dlg.show()

        # Run dialog event loop
        self.dlg.exec()

    def export_layers(self):
        """Prompt for an output folder and write requested export files."""
        if not hasattr(self, 'dlg'):
            return

        # Get Output folder to write files from user
        if not hasattr(self, 'last_output_dir'):
            self.last_output_dir = QgsProject.instance().absolutePath() or os.path.expanduser("~")
        output_dir = QFileDialog.getExistingDirectory(
            self.dlg,
            self.tr('Select export folder'),
            self.last_output_dir
        )
        if not output_dir:
            return
        self.last_output_dir = output_dir

        # Get selected layers and their requested export formats from UI
        root = self.dlg.layers_tree_qt.invisibleRootItem()
        selected_layers = []
        for index in range(root.childCount()):
            item = root.child(index)
            self._collect_selected_layers(item, selected_layers)

        # Write SLD files for selected layers if requested
        write_slds = self.dlg.options_checkbox_slds_qt.isChecked()
        if write_slds:
            self.dlg.log_text_browser_qt.append(f"Exporting SLD files for selected layers to: {output_dir}")
            for layer_name, layer, _ in selected_layers:
                if layer is None:
                    continue
                sld_text = self._get_layer_sld(layer)
                if sld_text is None:
                    continue
                sld_output_path = os.path.join(output_dir, f"{layer_name}.sld")
                with open(sld_output_path, 'w', encoding='utf-8') as handle:
                    handle.write(sld_text)

        # Set up data formats options
        transform_context = QgsCoordinateTransformContext()
        fgb_options = QgsVectorFileWriter.SaveVectorOptions()
        fgb_options.driverName = "FlatGeobuf"
        fgb_options.fileEncoding = "UTF-8"
        gj_options = QgsVectorFileWriter.SaveVectorOptions()
        gj_options.driverName = "GeoJSON"
        gj_options.fileEncoding = "UTF-8"

        # Write out data in requested formats
        for layer_name, layer, layer_format in selected_layers:
            if layer is None:
                continue

            if layer_format == "FlatGeoBuf":
                output_path = os.path.join(output_dir, f"{layer_name}.fgb")
                self.dlg.log_text_browser_qt.append(f"Exporting FlatGeobuf layer: {layer_name}.fgb")
                QgsVectorFileWriter.writeAsVectorFormatV3(layer, output_path, transform_context, fgb_options)
            elif layer_format == "GeoJSON":
                output_path = os.path.join(output_dir, f"{layer_name}.geojson")
                self.dlg.log_text_browser_qt.append(f"Exporting GeoJSON layer: {layer_name}.geojson")
                QgsVectorFileWriter.writeAsVectorFormatV3(layer, output_path, transform_context, gj_options)
            elif layer_format == "PMTile":
                # TBD: Implement PMTile export
                self.dlg.log_text_browser_qt.append(f"PMTile export not yet implemented for layer: {layer_name}")
            elif layer_format == "GeoParquet":
                # TBD: Implement GeoParquet export
                self.dlg.log_text_browser_qt.append(f"GeoParquet export not yet implemented for layer: {layer_name}")

        # Write map config file
        write_map = self.dlg.options_checkbox_map_qt.isChecked()
        if write_map:
            self.dlg.log_text_browser_qt.append(f"Exporting map config file to: {output_dir}")

            # Proof of concept: Write a simple map_config.js file with the list of selected layers
            map_config = "var fgbLayerList = [";
            for layer_name, layer, layer_format in selected_layers:
                map_config += f"'{layer_name}',"
            map_config += "];"
            map_output_path = os.path.join(output_dir, "map_config.js")
            with open(map_output_path, 'w', encoding='utf-8') as handle:
                handle.write(map_config)

        # TBD: Show export complete message as a Plugin status bar message or popup dialog
        self.dlg.log_text_browser_qt.append("Export complete!")

    def _collect_selected_layers(self, item, selected_layers):
        """Collect checked layers from the tree widget rows."""
        if item.childCount() == 0:
            widget = self.dlg.layers_tree_qt.itemWidget(item, 0)
            if widget is None:
                return

            checkbox = widget.findChild(QCheckBox)
            if checkbox is None or not checkbox.isChecked():
                return


            label_widget = widget.findChild(QLabel)
            layer_name = label_widget.text()
            format_combobox = widget.findChild(QComboBox)
            layer_format = format_combobox.currentText()

            layer_item = self._find_layer_by_name(layer_name)
            selected_layers.append((layer_name, layer_item, layer_format))
            return

        for child_index in range(item.childCount()):
            child_item = item.child(child_index)
            self._collect_selected_layers(child_item, selected_layers)

    def _find_layer_by_name(self, layer_name):
        """Find a layer in the current project by its tree name."""
        for layer in QgsProject.instance().mapLayers().values():
            if layer.name() == layer_name:
                return layer
        return None

    def _get_layer_sld(self, layer):
        """Return SLD content for a layer if it is available."""
        if layer is None:
            return None

        try:
            sld_text = None
            context = QgsSldExportContext()
            sld_text = layer.exportSldStyleV3(context)
            return sld_text.toString()
        except Exception:
            return None
